
## 2019-08-26

客户端 close 后仍然有调用, 报了 notice

    [2019-08-26 18:42:52 *25811.0]  NOTICE  swFactoryProcess_finish (ERROR 1005): connection[fd=1] does not exists.
